spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easytravel_db
    username: root
    password: topsa1566@@
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include: secret  # application-secret.yml 파일을 포함

# API 설정 (기본값들, secret 파일에서 오버라이드됨)
api:
  google-key: AIzaSyDgi6POr_cYuSaqVnsXpOEgMpinSDI12DU
  openai-key: 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
  weather-key: 9b577086f3680588d393326fafc5c98f
# GPT 설정
gpt:
  api:
    key: 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
    model: ${GPT_MODEL:gpt-4o-mini}
    timeout: ${GPT_TIMEOUT:60}
    itinerary-model: ${GPT_ITINERARY_MODEL:gpt-4o}

# 외부 API URL 설정
external:
  google:
    geocode-url: https://maps.googleapis.com/maps/api/geocode/json?address=%s&key=%s
  weather:
    forecast-url: https://api.openweathermap.org/data/2.5/forecast?lat=%s&lon=%s&appid=%s&units=metric&lang=kr
